name: evc
description: electric vehicle charging app.
version: 1.0.0+1

environment:
 sdk: '>=2.1.0 <3.0.0'

dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^0.1.2
 shared_preferences: ^0.5.2
 cached_network_image: ^1.1.1
 rxdart: ^0.21.0
 dio: ^2.1.10
 path_provider: ^0.5.0+1
 ant_icons: ^1.0.0
 google_sign_in: ^4.0.6
 provider: any
 google_maps_flutter: ^0.5.19+2
 location: ^2.3.5
 geolocator: ^5.1.1+1
 latlong: ^0.6.1
 firebase_core: ^0.3.4
 flutter_polyline_points: ^0.1.0
 firebase_auth: ^0.8.4+5
 firebase_analytics: ^2.1.1+3
 cloud_firestore: ^0.9.13+1

dev_dependencies:
 flutter_test:
  sdk: flutter

flutter:
 uses-material-design: true

 # To add assets to your application, add an assets section, like this:
 assets:
  - assets/images/
  - assets/icons/

 fonts:
  - family: Proxima
    fonts:
     - asset: assets/fonts/proxima-nova-soft-regular.otf
  - family: OpenSans
    fonts:
     - asset: assets/fonts/OpenSans-Regular.ttf
